---
input: "C:/Users/amarx/PycharmProjects/Morphelia/data/NRCMs_livecells_calceinam/"
output: "C:/Users/amarx/PycharmProjects/Morphelia/data/NRCMs_livecells_calceinam/"
output_fn: "cardio_ss"
# name of files with subsamples and aggregated data
agg_name: "morph_data_agg.h5ad" # don not forget suffix
ss_name: "morph_data_ss_10.h5ad"  # don not forget suffix

################################
# StoreAD
################################
to_disk: 'plate'  # 'plate', 'batch' or None
files:
  - "Cells.txt"
 # - "Primarieswithoutborder.csv"
 # - "Cytoplasm.csv"
treatment: "Treatment.csv"  # None if no treatment file exists

################################
# Pseudostitch
################################
stitched_name: 'morph_data_stitched.h5ad' # don not forget suffix
stitched_inp: 'ss_name'
tile_rows: 5
tile_cols: 5
img_overlap: 0.2

################################
# Preprocess
################################
pp_name: 'morph_data_pp.h5ad'  # don not forget suffix
pp_inp: 'stitched_name'
batch_id: "BatchNumber"
condition_group:
  - "Metadata_Treatment"
  - "Metadata_Concentration"
treat_var: 'Metadata_Treatment' # Metadata_[variable from Treatment.csv]
ctrl_name: 'ctrl' # name of control group in treat_var
norm_method: 'mad_robust' # one of standard, robust, mad_robust, min_max
filter_debris: False # Cell und Nuclei size needed

################################
# FeatureAgglo
################################
agglo_name: 'morph_data_agglo.h5ad' # don not forget suffix
agglo_inp: 'pp_name'
k: 'estimate' # 'estimate' or int
cluster_min: 2
cluster_max: 20 # min and max clusters

################################
# LMM
################################
lmm_name: 'morph_data_lmm.h5ad' # do not forged suffix
lmm_inp: 'agglo_name'
time_series: True
drop_low_sign: False # Drop Features with low significance

################################
# Embedding
################################
emb_name: 'morph_data_emb.h5ad'
emb_inp: 'agglo_name'
neighbors: 10
n_pcs: 40 # PCs for computing neighborhood graph
use_paga: False # Use PAGA for UMAP


...